
CREATE TABLESPACE BL_Data
  DATAFILE 'C:\app\Administrator\oradata\BirdLand\BLdata01.dbf'
  SIZE 10M
  REUSE
  AUTOEXTEND ON
  NEXT 512k
  MAXSIZE 200M;

CREATE TABLESPACE BL_Ind
  DATAFILE 'C:\app\Administrator\oradata\BirdLand\BLind01.dbf'
  SIZE 10M
  REUSE
  AUTOEXTEND ON
  NEXT 512k
  MAXSIZE 200M;


CREATE USER BL
      IDENTIFIED BY BL123
      DEFAULT TABLESPACE BL_data
      QUOTA 10M on BL_data
      TEMPORARY TABLESPACE temp
      QUOTA 5M ON system;

/* REVISAR CON CUIDADO */
GRANT ALL PRIVILEGES TO BL;

GRANT CONNECT TO BL;
GRANT CREATE TABLE TO BL;
GRANT CREATE PUBLIC SYNONYM TO BL;
GRANT CREATE VIEW TO BL;
GRANT CREATE ANY INDEX TO BL;
GRANT UNLIMITED TABLESPACE TO BL;
GRANT CREATE PROCEDURE to BL;
